"""
depthmap_to_obj.py
------------------
Convert a MiDaS depthmap PNG + original photo into a textured OBJ mesh.

Usage:
    python depthmap_to_obj.py --depth depthmap.png --photo photo.jpg --out output.obj

Works locally, no GPU needed.
"""

import argparse
import numpy as np
from PIL import Image, ImageFilter
import os

def depthmap_to_obj(depth_path, photo_path, out_path, scale=4, height_scale=0.4, smooth=1):
    print(f"Loading depth map: {depth_path}")
    depth_img = Image.open(depth_path).convert("L")

    print(f"Loading photo: {photo_path}")
    photo = Image.open(photo_path).convert("RGB")

    # Match sizes
    W, H = depth_img.size
    photo = photo.resize((W, H), Image.LANCZOS)

    # Downsample for mesh density
    MW, MH = W // scale, H // scale
    depth_small = np.array(depth_img.resize((MW, MH), Image.LANCZOS), dtype=np.float32) / 255.0
    photo_small = np.array(photo.resize((MW, MH), Image.LANCZOS), dtype=np.float32) / 255.0

    # Optional smoothing
    if smooth > 0:
        from PIL import ImageFilter
        d = Image.fromarray((depth_small * 255).astype("uint8"))
        for _ in range(smooth):
            d = d.filter(ImageFilter.GaussianBlur(1))
        depth_small = np.array(d, dtype=np.float32) / 255.0

    print(f"Building mesh: {MW}x{MH} = {MW*MH:,} verts")

    positions, colors, normals_list, uvs, indices = [], [], [], [], []

    for y in range(MH):
        for x in range(MW):
            vx = (x / (MW - 1)) * 2 - 1
            vy = -((y / (MH - 1)) * 2 - 1)
            vz = float(depth_small[y, x]) * height_scale
            positions.append((vx, vy, vz))
            r, g, b = photo_small[y, x, :3]
            colors.append((float(r), float(g), float(b)))
            uvs.append((x / (MW - 1), 1 - y / (MH - 1)))

    # Faces
    for y in range(MH - 1):
        for x in range(MW - 1):
            a = y * MW + x
            b = y * MW + x + 1
            c = (y + 1) * MW + x + 1
            d = (y + 1) * MW + x
            indices.extend([(a, b, c), (a, c, d)])

    # Normals
    pos_arr = np.array(positions)
    norms = np.zeros_like(pos_arr)
    for tri in indices:
        a, b, c = pos_arr[tri[0]], pos_arr[tri[1]], pos_arr[tri[2]]
        n = np.cross(b - a, c - a)
        l = np.linalg.norm(n)
        if l > 0:
            n /= l
            norms[tri[0]] += n
            norms[tri[1]] += n
            norms[tri[2]] += n
    lens = np.linalg.norm(norms, axis=1, keepdims=True)
    lens[lens == 0] = 1
    norms /= lens

    # Save texture
    tex_path = out_path.replace(".obj", "_texture.png")
    photo.save(tex_path)
    tex_name = os.path.basename(tex_path)
    mtl_path = out_path.replace(".obj", ".mtl")
    mtl_name = os.path.basename(mtl_path)

    with open(mtl_path, "w") as f:
        f.write(f"newmtl material0\n")
        f.write(f"map_Kd {tex_name}\n")

    print(f"Writing OBJ: {out_path}")
    with open(out_path, "w") as f:
        f.write("# Depthmap → OBJ mesh\n")
        f.write("# Generated by image-to-3d\n\n")
        f.write(f"mtllib {mtl_name}\n\n")
        for i, (v, c) in enumerate(zip(positions, colors)):
            f.write(f"v {v[0]:.4f} {v[1]:.4f} {v[2]:.4f} {c[0]:.3f} {c[1]:.3f} {c[2]:.3f}\n")
        f.write("\n")
        for uv in uvs:
            f.write(f"vt {uv[0]:.4f} {uv[1]:.4f}\n")
        f.write("\n")
        for n in norms:
            f.write(f"vn {n[0]:.4f} {n[1]:.4f} {n[2]:.4f}\n")
        f.write("\nusemtl material0\n\n")
        for tri in indices:
            a, b, c = tri[0]+1, tri[1]+1, tri[2]+1
            f.write(f"f {a}/{a}/{a} {b}/{b}/{b} {c}/{c}/{c}\n")

    print(f"✅ Done!")
    print(f"   OBJ:     {out_path}")
    print(f"   MTL:     {mtl_path}")
    print(f"   Texture: {tex_path}")
    print(f"\nLoad {os.path.basename(out_path)} in the 3D viewer HTML.")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Convert depthmap + photo to OBJ mesh")
    parser.add_argument("--depth", required=True, help="Depthmap PNG (grayscale, bright=close)")
    parser.add_argument("--photo", required=True, help="Original photo for texture")
    parser.add_argument("--out", default="output.obj", help="Output OBJ filename")
    parser.add_argument("--scale", type=int, default=4, help="Downsample factor (higher=fewer polys)")
    parser.add_argument("--height", type=float, default=0.4, help="Height exaggeration (0.1-1.0)")
    parser.add_argument("--smooth", type=int, default=1, help="Smoothing passes (0=none)")
    args = parser.parse_args()
    depthmap_to_obj(args.depth, args.photo, args.out, args.scale, args.height, args.smooth)
